function love.conf(t)
    t.title = "LURE"        		-- The title of the window the game is in (string)
    t.author = "Regan Laitila"  	-- The author of the game (string)
    t.identity = nil            	-- The name of the save directory (string)    
    t.console = false           		-- Attach a console (boolean, Windows only)
    t.window.width = 1027        	-- The window width (number)
    t.window.height = 768      		-- The window height (number)
    t.window.fullscreen = false 	-- Enable fullscreen (boolean)
    t.window.vsync = false       	-- Enable vertical sync (boolean)
    t.window.fsaa = 0           	-- The number of FSAA-buffers (number)
    t.modules.joystick = true   	-- Enable the joystick module (boolean)
    t.modules.audio = true      	-- Enable the audio module (boolean)
    t.modules.keyboard = true   	-- Enable the keyboard module (boolean)
    t.modules.event = true      	-- Enable the event module (boolean)
    t.modules.image = true      	-- Enable the image module (boolean)
    t.modules.graphics = true   	-- Enable the graphics module (boolean)
    t.modules.timer = true      	-- Enable the timer module (boolean)
    t.modules.mouse = true      	-- Enable the mouse module (boolean)
    t.modules.sound = true      	-- Enable the sound module (boolean)
    t.modules.physics = true    	-- Enable the physics module (boolean)
end